### PR TITLE
Update zlib to 1.2.13; change URL to persistent fossils index

### PR DESCRIPTION
**Pull request by Softdrink117**
I've been experimenting with libnaomi and ran into a few minor issues while setting up the dev environment:

- `make -C 3rdparty install` can fail if zlib is updated. The original version was 1.2.12; I had to update the `Makefile` to reference 1.2.13. 
- `make -C 3rdparty install` can fail if `unzip` is not installed (perhaps this is one of the standard prereqs you mentioned; I was setting up a completely fresh machine and needed to add it)
- When running `tests.bin` in Demul after finishing the environment setup, it threw multiple ROMFS assertion failures. I figured out this is because there is an expected `/tests/romfs/empty_dir` that is not included in the repo. I believe this folder is being ignored by git because it has no contents.
  - I think the simplest and cleanest solution to this would probably be ensuring the presence of the `empty_dir` by editing the `tests` Makefile; however, since I'm not very fluent in Makefiles myself, I've just added a note to the README as a stopgap

Absolutely amazing work on this repo; the amount of effort that's gone into it really shows. Can't wait to explore it further.

### CODE REVIEW

**Comment by DragonMinded** [comment]
I'm not surprised that some libs will fail if they get updated, since we can't control what other website authors decide to do with old files. The right solution there is exactly what you did, bump the version. As for the empty file thing, the README "hack" isn't great, I didn't realize this was an issue because I haven't bootstrapped and run tests from a completely fresh repo, good catch! The right answer is to add a mkdir call in the romfs dependency, I can do that. I can also make sure unzip is listed in the initial setup steps.

**Comment by DragonMinded** [comment]
Okay, I pushed a fix for the romfs issue and updated the README deps, could you give those a try? If so, the only relevant commit in this PR should be the zlib bump.

**Comment by Softdrink117** [comment]
Looks good to me. Just reverted my local copy, pulled your latest, made sure `empty_dir` didn't exist, rebuilt, and the `emtpy_dir` fix worked just fine. In retrospect I probably should've raised the `romfs` error as an issue rather than a PR; my apologies. Reverted the README changes.

It occurs to me that it would be possible to make the zlib URL consistent if it pointed to their `fossils` download archive instead of the main page; EG: [zlib.net/fossils/zlib-1.2.13.tar.gz](http://zlib.net/fossils/zlib-1.2.13.tar.gz). On the other hand however, it might actually be desirable to have occasional version bumps to keep the sources up-to-date.

**Comment by DragonMinded** [comment]
I think I'd prefer pointing at fossils so that builds don't break randomly. Setting up a new development environment and toolchain with a bunch of libraries is time-consuming and error-prone enough. Would hate to turn somebody away because they run into an issue like this and its non-obvious what to fix. Also doesn't feel like its on random newbs setting up the toolchain to discover issues in outdated deps.

**Comment by Softdrink117** [comment]
Alright, I just tweaked the Makefile again to point to the `fossils` download archive, and tested building again on this end.

I also went through the other `3rdparty` libs and made sure all the download links were persistent - it seems like zlib was the only one that wasn't already pointing to an index or archive.

**Comment by DragonMinded** [comment]
Hmm how did I miss this?

**Pull request merged**
